export enum IplayarrParameter {
    DEBUG = 'DEBUG',
    PORT = 'PORT',
    API_KEY = 'API_KEY',
    ACTIVE_LIMIT = 'ACTIVE_LIMIT',
    DOWNLOAD_DIR = 'DOWNLOAD_DIR',
    COMPLETE_DIR = 'COMPLETE_DIR',
    DOWNLOAD_CLIENT = 'DOWNLOAD_CLIENT',
    GET_IPLAYER_EXEC = 'GET_IPLAYER_EXEC',
    YTDLP_EXEC = 'YTDLP_EXEC',
    ADDITIONAL_IPLAYER_DOWNLOAD_PARAMS = 'ADDITIONAL_IPLAYER_DOWNLOAD_PARAMS',
    SUB_DIR = 'SUB_DIR',
    VIDEO_QUALITY = 'VIDEO_QUALITY',

    REFRESH_SCHEDULE = 'REFRESH_SCHEDULE',


    AUTH_TYPE = 'AUTH_TYPE',
    AUTH_USERNAME = 'AUTH_USERNAME',
    AUTH_PASSWORD = 'AUTH_PASSWORD',

    OIDC_CONFIG_URL = 'OIDC_CONFIG_URL',
    OIDC_CLIENT_ID = 'OIDC_CLIENT_ID',
    OIDC_CLIENT_SECRET = 'OIDC_CLIENT_SECRET',
    OIDC_CALLBACK_HOST = 'OIDC_CALLBACK_HOST',
    OIDC_ALLOWED_EMAILS = 'OIDC_ALLOWED_EMAILS',

    TV_FILENAME_TEMPLATE = 'TV_FILENAME_TEMPLATE',
    MOVIE_FILENAME_TEMPLATE = 'MOVIE_FILENAME_TEMPLATE',
    FALLBACK_FILENAME_SUFFIX = 'FALLBACK_FILENAME_SUFFIX',

    RSS_FEED_HOURS = 'RSS_FEED_HOURS',
    NATIVE_SEARCH = 'NATIVE_SEARCH',
    ARCHIVE_ENABLED = 'ARCHIVE_ENABLED',
    OUTPUT_FORMAT = 'OUTPUT_FORMAT',

    MEDIA_MODE = 'MEDIA_MODE',
    STREAM_BASE_URL = 'STREAM_BASE_URL',
    STREAM_MODE = 'STREAM_MODE',
    STREAM_CLIENT = 'STREAM_CLIENT',
    STREAM_CACHE_DIR = 'STREAM_CACHE_DIR',
    STREAM_KEY = 'STREAM_KEY',
    STREAM_NATIVE_ADAPTIVE = 'STREAM_NATIVE_ADAPTIVE',
    STREAM_NATIVE_HQ_PROBE = 'STREAM_NATIVE_HQ_PROBE',
    STREAM_NATIVE_EXPERIMENTAL_FHD = 'STREAM_NATIVE_EXPERIMENTAL_FHD'
}
