export enum IplayarrParameter {
    DEBUG = 'DEBUG',
    PORT = 'PORT',
    API_KEY = 'API_KEY',
    ACTIVE_LIMIT = 'ACTIVE_LIMIT',
    DOWNLOAD_DIR = 'DOWNLOAD_DIR',
    COMPLETE_DIR = 'COMPLETE_DIR',
    ARR_COMPLETE_DIR = 'ARR_COMPLETE_DIR',
    DOWNLOAD_CLIENT = 'DOWNLOAD_CLIENT',
    GET_IPLAYER_EXEC = 'GET_IPLAYER_EXEC',
    YTDLP_EXEC = 'YTDLP_EXEC',
    ADDITIONAL_IPLAYER_DOWNLOAD_PARAMS = 'ADDITIONAL_IPLAYER_DOWNLOAD_PARAMS',
    SUB_DIR = 'SUB_DIR',
    VIDEO_QUALITY = 'VIDEO_QUALITY',

    LIBRARY_FOLDER_STRUCTURE = 'LIBRARY_FOLDER_STRUCTURE',
    WRITE_NFO_STRM = 'WRITE_NFO_STRM',
    WRITE_STRMTOOL_JSON = 'WRITE_STRMTOOL_JSON',

    REFRESH_SCHEDULE = 'REFRESH_SCHEDULE',


    AUTH_TYPE = 'AUTH_TYPE',
    AUTH_USERNAME = 'AUTH_USERNAME',
    AUTH_PASSWORD = 'AUTH_PASSWORD',

    OIDC_CONFIG_URL = 'OIDC_CONFIG_URL',
    OIDC_CLIENT_ID = 'OIDC_CLIENT_ID',
    OIDC_CLIENT_SECRET = 'OIDC_CLIENT_SECRET',
    OIDC_CALLBACK_HOST = 'OIDC_CALLBACK_HOST',
    OIDC_ALLOWED_EMAILS = 'OIDC_ALLOWED_EMAILS',

    TV_FILENAME_TEMPLATE = 'TV_FILENAME_TEMPLATE',
    MOVIE_FILENAME_TEMPLATE = 'MOVIE_FILENAME_TEMPLATE',
    FALLBACK_FILENAME_SUFFIX = 'FALLBACK_FILENAME_SUFFIX',

    RSS_FEED_HOURS = 'RSS_FEED_HOURS',
    SCHEDULE_FULL_REFRESH = 'SCHEDULE_FULL_REFRESH',
    NATIVE_SEARCH = 'NATIVE_SEARCH',
    ARCHIVE_ENABLED = 'ARCHIVE_ENABLED',
    OUTPUT_FORMAT = 'OUTPUT_FORMAT',

    THUMBNAIL_CACHE_DIR = 'THUMBNAIL_CACHE_DIR',
    THUMBNAIL_RETENTION_DAYS = 'THUMBNAIL_RETENTION_DAYS',
    STREAM_HISTORY_RETENTION_DAYS = 'STREAM_HISTORY_RETENTION_DAYS',

    MEDIA_MODE = 'MEDIA_MODE',
    STREAM_BASE_URL = 'STREAM_BASE_URL',
    STREAM_MODE = 'STREAM_MODE',
    STREAM_CLIENT = 'STREAM_CLIENT',
    STREAM_CACHE_DIR = 'STREAM_CACHE_DIR',
    LIVE_STRM_DIR = 'LIVE_STRM_DIR',
    STREAM_KEY = 'STREAM_KEY',
    STREAM_NATIVE_ADAPTIVE = 'STREAM_NATIVE_ADAPTIVE',
    STREAM_NATIVE_HQ_PROBE = 'STREAM_NATIVE_HQ_PROBE',
    STREAM_NATIVE_EXPERIMENTAL_FHD = 'STREAM_NATIVE_EXPERIMENTAL_FHD',
    LIVE_TV_ENABLED = 'LIVE_TV_ENABLED',

    STRM_WATCHDOG_ENABLED = 'STRM_WATCHDOG_ENABLED',
    STRM_WATCHDOG_SOURCES = 'STRM_WATCHDOG_SOURCES',
    STRM_WATCHDOG_ACTION = 'STRM_WATCHDOG_ACTION',
    STRM_WATCHDOG_PATH_MAP = 'STRM_WATCHDOG_PATH_MAP',
    STRM_WATCHDOG_ARR_ACTION = 'STRM_WATCHDOG_ARR_ACTION',
    STRM_WATCHDOG_FAIL_THRESHOLD = 'STRM_WATCHDOG_FAIL_THRESHOLD',
    STRM_WATCHDOG_CONCURRENCY = 'STRM_WATCHDOG_CONCURRENCY',
    STRM_WATCHDOG_WEBHOOK_URL = 'STRM_WATCHDOG_WEBHOOK_URL'
}
