name: Lint

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev
    workflow_dispatch:

permissions:
    checks: write
    contents: write

jobs:
    run-linters:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: Install Node.js dependencies
              run: npm run install:both

            - name: Reset any package-lock changes backend
              run: git checkout -- package-lock.json

            - name: Reset any package-lock changes frontend
              run: git checkout -- frontend/package-lock.json

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                  eslint: true
